- name: Get list instance to deregister
  ec2_elb_facts:
    names: glabal-elb
    region: eu-west-1
  register: inctanse_to_deregister
- debug:
    var: inctanse_to_deregister

- name: add the webservers to the load balancer
  ec2_elb:
    state: present
    ec2_elbs: glabal-elb
    region: eu-west-1
    instance_id: "{{ item.id }}"
  with_items: "{{ec2_out.instances}}"

- name: Deregister old instance from ELB
  ec2_elb:
    state: 'absent'
    ec2_elbs: glabal-elb
    region: eu-west-1
    instance_id: "{{ item }}"
  with_items: "{{ inctanse_to_deregister.elbs.0.instances }}"

- name: Terminate old instance
  ec2:
    region: "{{ ec2.region }}"
    vpc_subnet_id: "{{ ec2.vpc_subnet_id }}"
    state: absent
    instance_ids: "{{ item }}"
  with_items: "{{ inctanse_to_deregister.elbs.0.instances }}"
