- name: Lunch ec2 instanse
  ec2:
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    instance_type: "{{ ec2.instance_type }}"
    group: "{{ ec2.group }}"
    image: "{{ ec2.image }}"
    keypair: "{{ ec2.keypair }}"
    region: "{{ ec2.region }}"
#    count: "{{ ec2.count }}"
    vpc_subnet_id: "{{ ec2.vpc_subnet_id }}"
    instance_tags: "{{ ec2.tags }}"
    exact_count: 1
    count_tag:
      application: global
    wait: yes
    assign_public_ip: yes
  register: ec2_out

- debug:
    var: ec2_out

- name: Add new instance to host group
  add_host:
    hostname: "{{ item.private_ip}}"
    groupname: launched
  with_items: "{{ ec2_out.instances }}"

- name: Wait for SSH to come up
  wait_for:
    host: "{{ item.private_ip }}"
    port: 22
    delay: 45
    timeout: 320
    state: started
  with_items: "{{ ec2_out.instances }}"
